# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nic30/Documents/workspace/hw_synthesis/hw_synthesis_helpers/cli_toolkit/vivado/samples/tmp/SampleBdProjectxc7z020clg484-2/SampleBdProjectxc7z020clg484-2.srcs/sources_1/pinConstr.xdc

# Block Designs: bd/test1/test1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test1 || ORIG_REF_NAME==test1}]

# XDC: bd/test1/test1_ooc.xdc
